apiVersion: v1
kind: ConfigMap
metadata:
  name: my-custom-scheduler-config
  namespace: kube-system
data:
  policy.cfg: |
    {
      "kind": "Policy",
      "apiVersion": "v1",
      "predicates": [
        {"name": "PodFitsHostPorts"},
        {"name": "PodFitsResources"},
        {"name": "NoDiskConflict"},
        {"name": "NoVolumeZoneConflict"},
        {"name": "MatchNodeSelector"},
        {"name": "HostName"}
      ],
      "priorities": [
        {"name": "LeastRequestedPriority", "weight": 1},
        {"name": "BalancedResourceAllocation", "weight": 1},
        {"name": "ServiceSpreadingPriority", "weight": 1},
        {"name": "EqualPriority", "weight": 1}
      ]
    }

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-custom-scheduler
  namespace: kube-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: my-custom-scheduler
  template:
    metadata:
      labels:
        component: my-custom-scheduler
    spec:
      serviceAccountName: my-custom-scheduler
      containers:
      - name: my-custom-scheduler
        image: k8s.gcr.io/kube-scheduler:v1.20.0
        command:
        - /usr/local/bin/kube-scheduler
        - --config=/etc/kubernetes/my-custom-scheduler-config.yaml
        volumeMounts:
        - name: config-volume
          mountPath: /etc/kubernetes/
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: my-custom-scheduler-config