apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
    tier: frontend
spec:
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
        type: front-end
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx

replicas: 3
selector:
  matchLabels:
    tier: frontend

# kubectl create -f rc-definition.yaml
# kubectl get rc/replicationcontrollers
# kubectl get pods
# replicationcontroller vs replica set
# ReplicationController ensures that a specified number of pod replicas are running at any one time.
# ReplicaSet is the next-generation ReplicationController and supports the new set-based label selector.
